default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: '123456789'
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: bingbing_development
test:
  <<: *default
  database: bingbing_test
production:
  <<: *default
  database: bingbing_production
  username: bingbing
  password: <%= ENV['BINGBING_DATABASE_PASSWORD'] %>
